### PR TITLE
removes Gambatte in the emulator resources

### PR DESCRIPTION
**Pull request by titibandit**
Gambatte is not available anymore. see https://github.com/sinamas/gambatte

### CODE REVIEW

**Comment by CasualPokePlayer** [comment]
Why not just replace the link with the currently active fork [Gambatte-Speedrun](https://github.com/pokemon-speedrunning/gambatte-speedrun), or [BizHawk](https://github.com/TASEmulators/BizHawk) which uses this fork's core.

**Comment by QuinnPainter** [comment]
also, the "complete list of open source emulators" link underneath can be removed as it is a 404

**Comment by avivace** [comment]
I pushed a mirror of the "historical" gambatte repository here: https://github.com/gb-archive/gambatte-mirror
But I'm pretty sure we should just link updated forks, so we should remove it

**Comment by pinobatch** [comment]
I'd be willing to include Gambatte so long as we're precise as to *which* Gambatte is most appropriate for a homebrew game developer.

- Last I checked, when I was [testing Numism in GB emulators](https://github.com/pinobatch/numism/blob/main/docs/gb_emu_testing.md), Gambatte-Speedrun's official front end was intended for the *Pokémon* speedrunning community, with the public builds structured so as to make it harder to accidentally produce a run whose RNG desynchronizes when replayed on Game Boy Player. Thus it has no HLE boot ROM and uses a CRC check to reject SameBoot. This makes the front end dependent on a non-free boot ROM, which is not end-user dumpable the way GBA-mode BIOS is and may not be lawfully distributed in any form that I know of, in order to work. I'd hate to see this list of resources get taken down for inducing infringement (*MGM v. Grokster*, 545 U.S. 913 (2005)).
- I have [forked the front end](https://github.com/pinobatch/gambatte-speedrun) to perform no CRC checks on the boot ROM, letting me use SameBoot. Between my day job and my obligations to other homebrew dev communities, I haven't yet had time to ask whether and how this modification could be taken upstream.
- The Gambatte core in BizHawk used to not work in Mono on Linux because of a cast from `unsigned int *` to `size_t *`, which produced undefined behavior that worked on Windows and failed on Linux. CasualPokePlayer has stated in the gbdev Discord server that this was fixed sometime before 2022-02-14.

**Comment by CasualPokePlayer** [comment]
https://github.com/pokemon-speedrunning/gambatte-core/commit/110b3eaab52667dd37d9c2df4bc72b820587e421
THis commit specifically fixed the issue on Mono, which was a few days before the release of BizHawk 2.8 (which has this fix).

As a note, past r717 bootrom skipping was re-introduced into the core (now it is just a simple load flag), which BizHawk allows to be enabled (and is enabled by default there). In the future Gambatte-Speedrun will have a "attempt" mode that locks down features and would allow the bootrom to be skipped outside of this mode (using the same bootrom skipping code in the core).

Suppose this doesn't cover GBC, but the MGB bootrom is possible to obtain without anything partiularly special by utilizing a dump of any of the Pokemon Stadium game, as they have an MGB bootrom embbed in them for use in the GB Tower.

**Comment by CasualPokePlayer** [comment]
> I pushed a mirror of the "historical" gambatte repository here: https://github.com/gb-archive/gambatte-mirror But I'm pretty sure we should just link updated forks, so we should remove it

What's the point of this when https://github.com/gb-archive/gambatte already existed?

**Comment by avivace** [comment]
> > I pushed a mirror of the "historical" gambatte repository here: https://github.com/gb-archive/gambatte-mirror But I'm pretty sure we should just link updated forks, so we should remove it
> 
> What's the point of this when https://github.com/gb-archive/gambatte already existed?

My bad, don't know why but I didn't see it.. I deleted gambatte-old now

**Comment by titibandit** [comment]
So yeah, I just noticed that the link was dead and wanted to remove it. But you guys have good suggestions, but I feel it's out of my power to take action here. So feel free to close/merge this pull request however you guys think is best.

**Review by avivace — APPROVED** [review]

**Comment by avivace** [comment]
I just noticed this change is in the gbdev.github.io repo. The resource page here is rendered from the awesome-gbdev list, so PRs should be opened upstream there, otherwise any change here will be overwritten.. @titibandit

**Comment by titibandit** [comment]
Okay I see.
I've used the link that's at the very bottom of https://gbdev.io/resources.html `Edit this page`.
So I've been tricked into making a pull request on this repo :D

**Pull request closed without merging**
